### ISSUE TITLE
after login error message

### ISSUE THREAD

**Issue by ksomasundaram1981** [WorldVistA/popHealth#192]
Hello

I have installed pophealth in Ubuntu 18.04 in the path /home/administrator/pophealth and when I login to the application it shows We're sorry, but something went wrong. However the registration page works. I use the default username / password.

Below is the error log

Processing by Devise::SessionsController#new as HTML
MONGODB | Detected PID change - Mongo client should have been reconnected (old pid 27988, new pid 28213
Redirected to http://vmnixpophealth01/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 24ms (MongoDB: 0.0ms)
Started GET "/" for 10.61.100.10 at 2021-01-12 01:03:35 +0000
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 11ms (MongoDB: 0.0ms)

NoMethodError (undefined method `each' for nil:NilClass):

app/controllers/home_controller.rb:38:in `transformcategories'
app/controllers/home_controller.rb:8:in `index'
Started GET "/users/sign_in" for 10.61.100.10 at 2021-01-12 01:03:42 +0000
Processing by Devise::SessionsController#new as HTML
Redirected to http://10.61.105.34/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 7ms (MongoDB: 0.0ms)
Started GET "/" for 10.61.100.10 at 2021-01-12 01:03:42 +0000
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 14ms (MongoDB: 0.0ms)

NoMethodError (undefined method `each' for nil:NilClass):

app/controllers/home_controller.rb:38:in `transformcategories'
app/controllers/home_controller.rb:8:in `index'
Started GET "/" for 10.61.100.10 at 2021-01-12 01:04:10 +0000
Processing by HomeController#index as HTML
Completed 401 Unauthorized in 5ms (MongoDB: 0.0ms)
Started GET "/users/sign_in" for 10.61.100.10 at 2021-01-12 01:04:10 +0000
Processing by Devise::SessionsController#new as HTML
  Rendering devise/sessions/new.html.erb within layouts/users
  Rendered devise/shared/_links.erb (2.9ms)
  Rendered devise/sessions/new.html.erb within layouts/users (10.1ms)
Completed 200 OK in 18ms (Views: 13.2ms | MongoDB: 0.0ms)
Started POST "/users/sign_in" for 10.61.100.10 at 2021-01-12 01:05:34 +0000
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wuK8gjrZTiMOkGvAqxtGnaNZYoO8xZAi856uQtwj5g1gVxe0+1xASE+rVE64Gt9nC1cVEigYS/SExs1GYcz4+Q==", "user"=>{"username"=>"pophealth", "password"=>"[FILTERED]"}, "commit"=>"Login"}
Redirected to http://10.61.105.34/
Completed 302 Found in 69ms (MongoDB: 0.0ms)
Started GET "/" for 10.61.100.10 at 2021-01-12 01:05:35 +0000
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 12ms (MongoDB: 0.0ms)

NoMethodError (undefined method `each' for nil:NilClass):

app/controllers/home_controller.rb:38:in `transformcategories'
app/controllers/home_controller.rb:8:in `index'

Can some one please help with this issues.

Thanks

**Comment by petercyli** [comment]
Can you check to see what is the version of MongoDB (Step 5 in the Installation guide <https://github.com/WorldVistA/popHealth/wiki/Installation-v6.1-(2020-Reporting-Period)> )?

 

Peter

**Comment by ksomasundaram1981** [comment]
Hi Peter,

Thanks for your response. I am using MongoDB server version: 3.6.21 as I couldn't install 3.4 on ubuntu 18.4. Will this cause any issue.

**Comment by petercyli** [comment]
We’ve had issues with 3.6; hence, we’ve fallen back to 3.4.x.

 

Any reason why you can’t install 3.4.x on ubuntu 18.4?

 

Peter

**Comment by ksomasundaram1981** [comment]
Thanks a lot peter. Changing the DB version to 3.4.24 worked.
